# Generated by Django 5.2.3 on 2025-06-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_answered',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_correct',
        ),
    ]
